### PR TITLE
Fix Segmentation example

### PR DESCRIPTION
**Pull request by unixxxx**
### Description
There's no `.length` on the `segmentationMask`, have to call `getAsFloat32Array()` first

Fixes # (153)

### Checklist
Please ensure the following items are complete before submitting a pull request:

- [x] My code follows the code style of the project.
- [ ] I have updated the documentation (if applicable).
- [ ] I have added tests to cover my changes.

### Type of Change
Please check the relevant option below:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update (non-breaking change which updates documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by PaulTR** [comment]
Hi @unixxxx, can you please accept the CLA for this? Thanks!

**Comment by unixxxx** [comment]
> Hi @unixxxx, can you please accept the CLA for this? Thanks!

Already accepted

**Review by unixxxx — COMMENTED** [review]
fix reading getAsFloat32Array of undefined

**Comment by unixxxx** [comment]
That's the result I got after doing the final changes

Screenshot 2023-06-02 at 03 22 52

**Comment by unixxxx** [comment]
@PaulTR Did you get the chance to check this after the last commit?

**Pull request merged**
